In [1]:
import pandas as pd

file = "../../data/cleaned/all-cleaned-merged-2022-06-22.csv"

df = pd.read_csv(file, encoding='utf-8')

df.head(10)

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,text,scrape_time,tweet_id,created_at,reply_count,quote_count,like_count,...,keywords,search_keywords,search_neighbourhood,geo,geo_full_name,geo_id,geo_bbox,tweet_coordinate,sentiment,score
0,26,26,26.0,@YasMohammedxx Come to Victoria. There are gr...,2022-04-10 13:54:17.244411,1.511161e+18,2022-04-05 01:57:28+00:00,1,0,3,...,Victoria Homelessness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27,27,27.0,TIL ‚Äúcamping‚Äù is another word for homelessness...,2022-04-10 13:54:17.244411,1.511001e+18,2022-04-04 15:21:00+00:00,0,0,0,...,Victoria Homelessness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28,28,28.0,"You are invited to learn: Skateboard Parks, Co...",2022-04-10 13:54:17.244411,1.510743e+18,2022-04-03 22:15:30+00:00,1,0,3,...,Victoria Homelessness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29,29,29.0,Some students in Victoria are experiencing hom...,2022-04-10 13:54:17.244411,1.510720e+18,2022-04-03 20:45:36+00:00,11,2,116,...,Victoria Homelessness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53,53,53.0,"Sure, meaningful employment can reduce recidiv...",2022-04-10 13:54:17.771372,1.511499e+18,2022-04-06 00:21:45+00:00,1,0,8,...,Victoria Poverty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,54,54,54.0,@MelissaLantsman Incorrect- I come from a gene...,2022-04-10 13:54:17.771372,1.511085e+18,2022-04-04 20:53:17+00:00,0,0,0,...,Victoria Poverty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,91,91,91.0,@CharlesBodi @BC_Housing @CityOfVictoria @Adam...,2022-04-10 13:54:18.557148,1.512066e+18,2022-04-07 13:51:27+00:00,0,0,1,...,Victoria Shelter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,98,98,98.0,"SAD NEWS üòøüòøBlack, intact Male, domestic short-...",2022-04-10 13:54:18.557148,1.511225e+18,2022-04-05 06:10:31+00:00,0,0,0,...,Victoria Shelter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,99,99,99.0,A5467037 ‚ú∞ WOOFY -3/22/22-\r\nüò¢OWNER SURRENDER...,2022-04-10 13:54:18.557148,1.511145e+18,2022-04-05 00:51:57+00:00,1,0,0,...,Victoria Shelter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,100,100,100.0,9YR OLD ROSCO #A5464109 IS GOING TO DIE TODAY ...,2022-04-10 13:54:18.557148,1.511013e+18,2022-04-04 16:09:02+00:00,5,3,25,...,Victoria Shelter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.shape

(14260, 23)

In [3]:
df['search_keywords']

0                                                      NaN
1                                                      NaN
2                                                      NaN
3                                                      NaN
4                                                      NaN
                               ...
14255    (from:katstinson OR from:chartj88 OR from:bern...
14256    (from:majatait OR from:adriandix OR from:r_gar...
14257    (from:majatait OR from:adriandix OR from:r_gar...
14258    (from:majatait OR from:adriandix OR from:r_gar...
14259    (from:majatait OR from:adriandix OR from:r_gar...
Name: search_keywords, Length: 14260, dtype: object

In [4]:
BADWORDS = ['camp', 'camping', 'tent', 'ops', 'poor', 'crime']
BADWORDS += ["Trump", "Cuomo", "SF", "NYC", 'NY', 'Australia', 'Melbourne', 'Geelong']

df1 = df.copy()

for bad in BADWORDS:
    df1 = df1[~df1["text"].str.lower().str.contains(bad.lower())]

df1.shape

(8253, 23)

In [5]:
BADQUERY = ['Central Park', 'Gorge', 'sidney', 'gonzales', 'north park', 'rockland']

df2 = df.copy()

df2 = df2[df2['search_keywords'].notna()]

df2.shape

(14244, 23)

In [6]:
for bad in BADQUERY:
    df2 = df2[~df2["search_keywords"].str.lower().str.contains(bad.lower())]

df2.shape

(10999, 23)

In [8]:
df1 = df1[df1['search_keywords'].notna()]

for bad in BADQUERY:
    df1 = df1[~df1["search_keywords"].str.lower().str.contains(bad.lower())]

df1.shape

(6733, 23)

In [29]:
newdf = df.sample(n=210)

In [30]:
newdf['relevant'] = ''
newdf = newdf.reset_index()
newdf = newdf.assign(g=newdf.index//30)
newdf

,index,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,text,scrape_time,tweet_id,created_at,reply_count,quote_count,...,search_neighbourhood,geo,geo_full_name,geo_id,geo_bbox,tweet_coordinate,sentiment,score,relevant,g
0,10616,21882,2208,NaN,"""There were 144 burglaries or break-ins in Bri...",2022-05-30 22:49:59.202327,1.531403e+18,2022-05-30 22:32:27+00:00,0,0,...,Victoria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0
1,1611,4789,445,NaN,Exactly. Get rid of cars. Create housing downt...,2022-04-21 17:09:34.071720,1.517228e+18,2022-04-21 19:46:43+00:00,0,0,...,downtown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0
2,11272,22918,13,NaN,@DRmVonNostrand @SBS0311 @SyryloChad @CapFrien...,2022-06-13 13:32:19.154775,1.536070e+18,2022-06-12 19:35:28+00:00,0,0,...,colwood OR sidney OR cook street village OR ro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0
3,8985,18597,1186,NaN,NEW: ‚ÄòHe will never change.‚Äô Ex-Miami-Dade cop...,2022-05-23 10:15:11.875444,1.527687e+18,2022-05-20 16:26:06+00:00,1,1,...,gonzalez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0
4,4700,11252,464,NaN,Downtown Baltimore saw slight rebound in emplo...,2022-05-09 23:20:23.585069,1.523664e+18,2022-05-09 14:01:17+00:00,0,0,...,downtown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,10071,20991,1317,NaN,beyond wonderland is a full send &amp; i could...,2022-05-30 22:48:11.188583,1.530303e+18,2022-05-27 21:38:51+00:00,1,0,...,sooke OR gonzales OR foul bay OR the gorge OR ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,6
206,12718,25879,2974,NaN,Fire at homeless encampment in Nanaimo\n\nNeig...,2022-06-13 13:40:26.661966,1.534526e+18,2022-06-08 13:21:48+00:00,1,0,...,individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,6
207,5186,11848,1060,NaN,@BuzzPatterson Never forget the famous quote f...,2022-05-09 23:21:19.645255,1.522632e+18,2022-05-06 17:38:37+00:00,0,0,...,gonzalez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,6
208,4595,11104,316,NaN,Officers responded the the scene at 1:46 a.m. ...,2022-05-09 23:20:17.829402,1.523733e+18,2022-05-09 18:35:05+00:00,0,0,...,fairfield,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,6
209,13320,27671,1749,NaN,SYSTEMIC RACISM &amp; HATE IS WHY @jjhorgan @B...,2022-06-20 13:33:39.094397,1.538628e+18,2022-06-19 21:01:59+00:00,0,0,...,saanich OR uplands OR quadra village OR centra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,6

In [31]:
list(newdf.columns)

['index',
 'Unnamed: 0.2',
 'Unnamed: 0.1',
 'Unnamed: 0',
 'text',
 'scrape_time',
 'tweet_id',
 'created_at',
 'reply_count',
 'quote_count',
 'like_count',
 'retweet_count',
 'username',
 'num_followers',
 'keywords',
 'search_keywords',
 'search_neighbourhood',
 'geo',
 'geo_full_name',
 'geo_id',
 'geo_bbox',
 'tweet_coordinate',
 'sentiment',
 'score',
 'relevant',
 'g']

In [32]:
newdf = newdf[['g', 'text', 'scrape_time', 'tweet_id', 'created_at', 'username', 'search_keywords', 'relevant']]

newdf

,text,scrape_time,tweet_id,created_at,username,keywords,search_keywords,relevant,g
0,"""There were 144 burglaries or break-ins in Bri...",2022-05-30 22:49:59.202327,1.531403e+18,2022-05-30 22:32:27+00:00,vcrepodcast,NaN,Victoria (avi OR cool aid society OR homelessn...,,0
1,Exactly. Get rid of cars. Create housing downt...,2022-04-21 17:09:34.071720,1.517228e+18,2022-04-21 19:46:43+00:00,privatecitizenn,NaN,downtown (bc housing OR vreb OR umbrella socie...,,0
2,@DRmVonNostrand @SBS0311 @SyryloChad @CapFrien...,2022-06-13 13:32:19.154775,1.536070e+18,2022-06-12 19:35:28+00:00,DannyDimesSzn8,NaN,(colwood OR sidney OR cook street village OR r...,,0
3,NEW: ‚ÄòHe will never change.‚Äô Ex-Miami-Dade cop...,2022-05-23 10:15:11.875444,1.527687e+18,2022-05-20 16:26:06+00:00,DavidOvalle305,NaN,gonzalez (aboriginal coalition to end homeless...,,0
4,Downtown Baltimore saw slight rebound in emplo...,2022-05-09 23:20:23.585069,1.523664e+18,2022-05-09 14:01:17+00:00,LyonsReports,NaN,downtown (bc housing OR vreb OR umbrella socie...,,0
...,...,...,...,...,...,...,...,...,...
205,beyond wonderland is a full send &amp; i could...,2022-05-30 22:48:11.188583,1.530303e+18,2022-05-27 21:38:51+00:00,ThatSmolCat,NaN,(sooke OR gonzales OR foul bay OR the gorge OR...,,6
206,Fire at homeless encampment in Nanaimo\n\nNeig...,2022-06-13 13:40:26.661966,1.534526e+18,2022-06-08 13:21:48+00:00,CharlesBodi,NaN,(from:charlesbodi OR from:nicolechaland OR fro...,,6
207,@BuzzPatterson Never forget the famous quote f...,2022-05-09 23:21:19.645255,1.522632e+18,2022-05-06 17:38:37+00:00,WeThePatientsNY,NaN,gonzalez (island health OR peers victoria reso...,,6
208,Officers responded the the scene at 1:46 a.m. ...,2022-05-09 23:20:17.829402,1.523733e+18,2022-05-09 18:35:05+00:00,RegionalPlan,NaN,fairfield (the aboriginal coalition to end hom...,,6
209,SYSTEMIC RACISM &amp; HATE IS WHY @jjhorgan @B...,2022-06-20 13:33:39.094397,1.538628e+18,2022-06-19 21:01:59+00:00,HatedByBCgovt,NaN,(saanich OR uplands OR quadra village OR centr...,,6

In [33]:
for i, dfg in newdf.groupby('g'):
    dfg.to_csv(f"verification-{i}.csv", encoding='utf-8')